# Generated by Django 3.2.8 on 2022-07-27 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=50, null=True)),
                ('Address_Line_1', models.CharField(blank=True, help_text='Address Line 1', max_length=70, null=True)),
                ('Address_Line_2', models.CharField(blank=True, help_text='Address Line 2', max_length=70, null=True)),
                ('Pin_Code', models.CharField(blank=True, help_text='pin code', max_length=6, null=True)),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Haryana', 'Haryana'), ('West Bengal', 'West Bengal'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir ', 'Jammu & Kashmir '), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Orissa', 'Orissa'), ('Sikkim', 'Sikkim'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman & Diu', 'Daman & Diu'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=50, null=True)),
                ('GST_No', models.CharField(blank=True, help_text='Provide If Company under GST', max_length=15, null=True)),
                ('CIN_No', models.CharField(blank=True, help_text='CIN No if available', max_length=30, null=True)),
                ('LUT_No', models.CharField(blank=True, help_text='LUT No if available', max_length=25, null=True)),
                ('State_Code', models.IntegerField(blank=True, help_text='State Code Ex. 36, 37', null=True)),
                ('Phone_Number_1', models.CharField(help_text='Main Phone Number', max_length=20, null=True)),
                ('Phone_Number_2', models.CharField(blank=True, help_text='Optional Phone Number', max_length=10, null=True)),
                ('Email', models.EmailField(help_text='Company Contact Mail Address', max_length=40, null=True)),
                ('Website', models.CharField(blank=True, max_length=40, null=True)),
                ('Address_Type', models.CharField(blank=True, choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Branch', 'Branch'), ('Manufacturing', 'Manufacturing'), ('Service', 'Service')], max_length=40, null=True)),
                ('Active_From', models.DateField(blank=True, help_text='If leave this, it will take today date', null=True)),
                ('Status', models.BooleanField(default=True, help_text='Unmark if Company Address not in Active')),
                ('ds', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='No_Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Format_Related_To', models.CharField(choices=[('Invoice', 'Invoice'), ('Proforma Invoice', 'Proforma Invoice'), ('PO', 'PO'), ('DC', 'DC'), ('Expenses Voucher', 'Expenses Voucher')], max_length=20, null=True)),
                ('No_Format', models.CharField(help_text='excluding financial year and sequence number such as PS/AP/Service/ etc..', max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(help_text='Project Name Such as Rooftop, Solar Pumps', max_length=50, null=True, unique=True)),
                ('Short_Name', models.CharField(help_text='Nick Name or Short Name of Project', max_length=15, null=True, unique=True)),
                ('Date', models.DateField(blank=True, help_text='Project Creation Date', null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], max_length=15, null=True)),
                ('ds', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_Name', models.CharField(help_text='Vendor/Supplier Name', max_length=50, null=True)),
                ('Short_Name', models.CharField(help_text='Give Short Name for Supplier, Max 15 Characters', max_length=15, null=True)),
                ('Address_Line_1', models.CharField(blank=True, help_text='Address Line 1', max_length=70, null=True)),
                ('Address_Line_2', models.CharField(blank=True, help_text='Address Line 2', max_length=70, null=True)),
                ('Pin_Code', models.CharField(blank=True, help_text='pin code', max_length=6, null=True)),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Haryana', 'Haryana'), ('West Bengal', 'West Bengal'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir ', 'Jammu & Kashmir '), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Orissa', 'Orissa'), ('Sikkim', 'Sikkim'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman & Diu', 'Daman & Diu'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=50, null=True)),
                ('GST_No', models.CharField(blank=True, help_text='Provide If Company under GST', max_length=15, null=True)),
                ('State_Code', models.IntegerField(blank=True, help_text='State Code Ex. 36, 37', null=True)),
                ('Phone_Number_1', models.CharField(help_text='Main Contact Phone Number', max_length=20, null=True)),
                ('Phone_Number_2', models.CharField(blank=True, help_text='Optional/Alternative Phone Number', max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, help_text='Customer/Company Contact Mail Address', max_length=40, null=True)),
                ('Website', models.CharField(blank=True, help_text='Official Website, Format: wwww.xyz.com only', max_length=40, null=True)),
                ('Address_Type', models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Branch', 'Branch'), ('Manufacturing', 'Manufacturing'), ('Service', 'Service')], max_length=40, null=True)),
                ('Supplier_Product_Details', models.TextField(blank=True, help_text='Supplier Product Details - Shortly', max_length=200, null=True)),
                ('Status', models.BooleanField(default=True, help_text='Unmark if Supplier is not in Active')),
                ('Active_From', models.DateField(blank=True, help_text='If leave this, it will take today date', null=True)),
                ('Attach_Doc', models.FileField(blank=True, help_text='Upload if any reference document', null=True, upload_to='vendors/')),
                ('ds', models.BooleanField(default=True)),
                ('Related_Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='VendContDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Person', models.CharField(help_text='Contact Person Name', max_length=30, null=True)),
                ('Phone_Number_1', models.CharField(help_text='Main Contact Phone Number', max_length=20, null=True)),
                ('Phone_Number_2', models.CharField(blank=True, help_text='Optional/Alternative Phone Number', max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, help_text='Contact Person Email', max_length=50, null=True)),
                ('Designation', models.CharField(blank=True, help_text='Specify if any', max_length=30, null=True)),
                ('Department', models.CharField(blank=True, help_text='Specify if any', max_length=30, null=True)),
                ('Other_Info', models.TextField(blank=True, help_text='Specify if want to give extra info.', max_length=200, null=True)),
                ('ds', models.BooleanField(default=True)),
                ('Supplier_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.venddt')),
            ],
        ),
        migrations.CreateModel(
            name='CustDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(help_text='Customer/Company Name', max_length=50, null=True)),
                ('Short_Name', models.CharField(help_text='Give Short Name for Customer, Max 15 Characters', max_length=15, null=True)),
                ('Address_Line_1', models.CharField(blank=True, help_text='Address Line 1', max_length=70, null=True)),
                ('Address_Line_2', models.CharField(blank=True, help_text='Address Line 2', max_length=70, null=True)),
                ('Pin_Code', models.CharField(blank=True, help_text='pin code', max_length=6, null=True)),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Haryana', 'Haryana'), ('West Bengal', 'West Bengal'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir ', 'Jammu & Kashmir '), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Orissa', 'Orissa'), ('Sikkim', 'Sikkim'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman & Diu', 'Daman & Diu'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=50, null=True)),
                ('GST_No', models.CharField(blank=True, help_text='Provide If Company under GST', max_length=15, null=True)),
                ('State_Code', models.IntegerField(blank=True, help_text='State Code Ex. 36, 37', null=True)),
                ('Phone_Number_1', models.CharField(help_text='Main Contact Phone Number', max_length=20, null=True)),
                ('Phone_Number_2', models.CharField(blank=True, help_text='Optional/Alternative Phone Number', max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, help_text='Customer/Company Contact Mail Address', max_length=40, null=True)),
                ('Website', models.CharField(blank=True, help_text='Official Website, Format: wwww.xyz.com only', max_length=40, null=True)),
                ('Address_Type', models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Branch', 'Branch'), ('Manufacturing', 'Manufacturing'), ('Service', 'Service')], max_length=40, null=True)),
                ('Active_From', models.DateField(blank=True, help_text='If leave this, it will take today date', null=True)),
                ('Status', models.BooleanField(default=True, help_text='Unmark if Company is not in Active')),
                ('Attach_Doc', models.FileField(blank=True, help_text='Upload if any reference document', null=True, upload_to='customers/')),
                ('ds', models.BooleanField(default=True)),
                ('Related_Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='CustContDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Person', models.CharField(help_text='Contact Person Name', max_length=30, null=True)),
                ('Phone_Number_1', models.CharField(help_text='Main Contact Phone Number', max_length=20, null=True)),
                ('Phone_Number_2', models.CharField(blank=True, help_text='Optional/Alternative Phone Number', max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, help_text='Contact Person Email', max_length=50, null=True)),
                ('Designation', models.CharField(blank=True, help_text='Specify if any', max_length=30, null=True)),
                ('Department', models.CharField(blank=True, help_text='Specify if any', max_length=30, null=True)),
                ('Other_Info', models.TextField(blank=True, help_text='Specify if want to give extra info.', max_length=200, null=True)),
                ('ds', models.BooleanField(default=True)),
                ('Customer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.custdt')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_No', models.CharField(help_text='Bank Account Number', max_length=40, null=True)),
                ('Bank_Name', models.CharField(help_text='Bank Name', max_length=30, null=True)),
                ('Branch', models.CharField(blank=True, help_text='bank branch details', max_length=40, null=True)),
                ('IFSC_Code', models.CharField(blank=True, help_text='bank IFSC code', max_length=11, null=True)),
                ('Account_Type', models.CharField(choices=[('CC', 'CC'), ('Current', 'Current')], max_length=40, null=True)),
                ('Status', models.BooleanField(default=True, help_text='active status')),
                ('Related_Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails')),
            ],
        ),
    ]
