# Generated by Django 3.2.8 on 2022-04-16 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(help_text='Project Name Such as Rooftop, Solar Pumps', max_length=50, null=True, unique=True)),
                ('Short_Name', models.CharField(help_text='Nick Name or Short Name of Project', max_length=15, null=True, unique=True)),
                ('Date', models.DateField(blank=True, help_text='Project Creation Date', null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], max_length=15, null=True)),
                ('ds', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
