# Generated by Django 3.2.8 on 2022-06-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='no_formats',
            old_name='PO_No_Format',
            new_name='No_Format',
        ),
    ]
