# Generated by Django 3.2.8 on 2022-09-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='IDS',
        ),
    ]
