# Generated by Django 3.2.8 on 2022-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_remove_ledger_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='Row_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
