# Generated by Django 3.2.8 on 2022-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_alter_no_formats_no_format_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='Address_Line_1',
            field=models.CharField(blank=True, help_text='Address Line 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='Address_Line_2',
            field=models.CharField(blank=True, help_text='Address Line 2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='Company_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custdt',
            name='Address_Line_1',
            field=models.CharField(blank=True, help_text='Address Line 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custdt',
            name='Address_Line_2',
            field=models.CharField(blank=True, help_text='Address Line 2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venddt',
            name='Address_Line_1',
            field=models.CharField(blank=True, help_text='Address Line 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venddt',
            name='Address_Line_2',
            field=models.CharField(blank=True, help_text='Address Line 2', max_length=50, null=True),
        ),
    ]
