# Generated by Django 3.2.8 on 2022-09-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_ledger_row_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
