# Generated by Django 3.2.8 on 2022-09-19 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_ledger_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Partner', models.CharField(blank=True, max_length=100, null=True)),
                ('Ref_No', models.CharField(blank=True, max_length=30, null=True)),
                ('Order_No', models.CharField(blank=True, max_length=30, null=True)),
                ('Debit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Lock_Status', models.BooleanField(default=True)),
                ('Row_ID', models.IntegerField(blank=True, null=True, unique=True)),
                ('Related_Project', models.ForeignKey(blank=True, help_text='leave empty if product meant for many projects', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Partner', models.CharField(blank=True, max_length=100, null=True)),
                ('Ref_No', models.CharField(blank=True, max_length=30, null=True)),
                ('Order_No', models.CharField(blank=True, max_length=30, null=True)),
                ('Debit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Lock_Status', models.BooleanField(default=True)),
                ('Row_ID', models.IntegerField(blank=True, null=True, unique=True)),
                ('Related_Project', models.ForeignKey(blank=True, help_text='leave empty if product meant for many projects', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
