# Generated by Django 3.2.8 on 2022-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_companydetails_custcontdt_custdt_vendcontdt_venddt'),
    ]

    operations = [
        migrations.AddField(
            model_name='custdt',
            name='Attach_Doc',
            field=models.FileField(blank=True, help_text='Upload if any reference document', null=True, upload_to='customers/'),
        ),
        migrations.AddField(
            model_name='venddt',
            name='Attach_Doc',
            field=models.FileField(blank=True, help_text='Upload if any reference document', null=True, upload_to='vendors/'),
        ),
    ]
