# Generated by Django 3.2.8 on 2022-09-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20220919_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_ledger',
            name='Lock_Status',
        ),
        migrations.RemoveField(
            model_name='vendor_ledger',
            name='Lock_Status',
        ),
    ]
