# Generated by Django 3.2.8 on 2022-09-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20220919_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_ledger',
            name='Lock_Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor_ledger',
            name='Lock_Status',
            field=models.BooleanField(default=True),
        ),
    ]
