# Generated by Django 3.2.8 on 2022-05-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20220502_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='Name',
            new_name='Company_Name',
        ),
        migrations.AlterField(
            model_name='custcontdt',
            name='Customer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.custdt'),
        ),
        migrations.AlterField(
            model_name='custdt',
            name='Website',
            field=models.CharField(blank=True, help_text='Official Website, Format: wwww.xyz.com only', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='venddt',
            name='Website',
            field=models.CharField(blank=True, help_text='Official Website, Format: wwww.xyz.com only', max_length=40, null=True),
        ),
    ]
