# Generated by Django 3.2.8 on 2022-09-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20220919_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_ledger',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_ledger',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
