# Generated by Django 3.2.8 on 2022-09-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20220919_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_ledger',
            name='Sr_No',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor_ledger',
            name='Sr_No',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
