# Generated by Django 3.2.8 on 2022-05-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20220503_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontdt',
            name='Customer_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.custdt'),
        ),
    ]
