# Generated by Django 3.2.8 on 2022-05-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_alter_custcontdt_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontdt',
            name='Customer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.custdt'),
        ),
    ]
