# Generated by Django 3.2.8 on 2022-05-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_alter_custcontdt_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendcontdt',
            name='Supplier_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.venddt'),
        ),
    ]
