# Generated by Django 3.2.8 on 2022-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0011_auto_20220920_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_ledger',
            name='Sr_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_ledger',
            name='Sr_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
