# Generated by Django 3.2.8 on 2022-09-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_auto_20220920_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_ledger',
            name='Row_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_ledger',
            name='Row_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
