# Generated by Django 3.2.8 on 2022-10-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0013_auto_20220920_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_ledger',
            old_name='Bal_Customer',
            new_name='Bal_Vendor',
        ),
    ]
