# Generated by Django 3.2.8 on 2022-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0016_auto_20221022_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='State_Code',
            field=models.CharField(blank=True, choices=[('37', 'Andhra Pradesh'), ('36', 'Telangana'), ('33', 'Tamil Nadu'), ('29', 'Karnataka'), ('27', 'Maharashtra'), ('32', 'Kerala'), ('22', 'Chhattisgarh'), ('07', 'Delhi'), ('30', 'Goa'), ('24', 'Gujarat'), ('03', 'Punjab'), ('08', 'Rajasthan'), ('06', 'Haryana'), ('19', 'West Bengal'), ('02', 'Himachal Pradesh'), ('01 ', 'Jammu & Kashmir '), ('20', 'Jharkhand'), ('12 ', 'Arunachal Pradesh '), ('18', 'Assam'), ('10', 'Bihar'), ('23', 'Madhya Pradesh'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Orissa'), ('11', 'Sikkim'), ('16', 'Tripura'), ('09', 'Uttar Pradesh'), ('05', 'Uttarakhand'), ('35', 'Andaman & Nicobar Islands'), ('04', 'Chandigarh'), ('26', 'Dadra & Nagar Haveli'), ('25', 'Daman & Diu'), ('31', 'Lakshadweep'), ('34', 'Puducherry')], help_text='State Code Ex. 36, 37', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='custdt',
            name='State_Code',
            field=models.CharField(blank=True, choices=[('37', 'Andhra Pradesh'), ('36', 'Telangana'), ('33', 'Tamil Nadu'), ('29', 'Karnataka'), ('27', 'Maharashtra'), ('32', 'Kerala'), ('22', 'Chhattisgarh'), ('07', 'Delhi'), ('30', 'Goa'), ('24', 'Gujarat'), ('03', 'Punjab'), ('08', 'Rajasthan'), ('06', 'Haryana'), ('19', 'West Bengal'), ('02', 'Himachal Pradesh'), ('01 ', 'Jammu & Kashmir '), ('20', 'Jharkhand'), ('12 ', 'Arunachal Pradesh '), ('18', 'Assam'), ('10', 'Bihar'), ('23', 'Madhya Pradesh'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Orissa'), ('11', 'Sikkim'), ('16', 'Tripura'), ('09', 'Uttar Pradesh'), ('05', 'Uttarakhand'), ('35', 'Andaman & Nicobar Islands'), ('04', 'Chandigarh'), ('26', 'Dadra & Nagar Haveli'), ('25', 'Daman & Diu'), ('31', 'Lakshadweep'), ('34', 'Puducherry')], help_text='State Code Ex. 36, 37', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='venddt',
            name='State_Code',
            field=models.CharField(blank=True, choices=[('37', 'Andhra Pradesh'), ('36', 'Telangana'), ('33', 'Tamil Nadu'), ('29', 'Karnataka'), ('27', 'Maharashtra'), ('32', 'Kerala'), ('22', 'Chhattisgarh'), ('07', 'Delhi'), ('30', 'Goa'), ('24', 'Gujarat'), ('03', 'Punjab'), ('08', 'Rajasthan'), ('06', 'Haryana'), ('19', 'West Bengal'), ('02', 'Himachal Pradesh'), ('01 ', 'Jammu & Kashmir '), ('20', 'Jharkhand'), ('12 ', 'Arunachal Pradesh '), ('18', 'Assam'), ('10', 'Bihar'), ('23', 'Madhya Pradesh'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Orissa'), ('11', 'Sikkim'), ('16', 'Tripura'), ('09', 'Uttar Pradesh'), ('05', 'Uttarakhand'), ('35', 'Andaman & Nicobar Islands'), ('04', 'Chandigarh'), ('26', 'Dadra & Nagar Haveli'), ('25', 'Daman & Diu'), ('31', 'Lakshadweep'), ('34', 'Puducherry')], help_text='State Code Ex. 36, 37', max_length=30, null=True),
        ),
    ]
