# Generated by Django 3.2.8 on 2022-10-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0017_auto_20221022_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='State_Code',
            field=models.IntegerField(blank=True, help_text='State Code Ex. 36, 37', null=True),
        ),
        migrations.AlterField(
            model_name='custdt',
            name='Short_Name',
            field=models.CharField(help_text='Give Short Name for Customer, Max 25 Characters', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='custdt',
            name='State_Code',
            field=models.IntegerField(blank=True, help_text='State Code Ex. 36, 37', null=True),
        ),
        migrations.AlterField(
            model_name='venddt',
            name='Short_Name',
            field=models.CharField(help_text='Give Short Name for Supplier, Max 25 Characters', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='venddt',
            name='State_Code',
            field=models.IntegerField(blank=True, help_text='State Code Ex. 36, 37', null=True),
        ),
    ]
