# Generated by Django 3.2.8 on 2022-10-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0015_empl_salaries_effective_from'),
        ('Projects', '0018_auto_20221025_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page', models.CharField(blank=True, max_length=100, null=True)),
                ('RC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails')),
                ('Related_Project', models.ForeignKey(blank=True, help_text='leave empty if product meant for many projects', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='View_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page', models.CharField(blank=True, max_length=100, null=True)),
                ('RC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails')),
                ('Related_Project', models.ForeignKey(blank=True, help_text='leave empty if product meant for many projects', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Page_Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Edit_Permissions', models.ManyToManyField(blank=True, null=True, to='Projects.Edit_Pages')),
                ('Given_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_account', to='UserAccounts.account')),
                ('RC', models.ManyToManyField(blank=True, null=True, to='Projects.CompanyDetails')),
                ('Related_Project', models.ManyToManyField(blank=True, null=True, to='Projects.Projects')),
                ('View_Permissions', models.ManyToManyField(blank=True, null=True, to='Projects.View_Pages')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Permissions_account', to='UserAccounts.account')),
            ],
        ),
    ]
