# Generated by Django 3.2.8 on 2022-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0019_edit_pages_page_permissions_view_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_permissions',
            name='Is_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
