# Generated by Django 3.2.8 on 2022-11-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0020_page_permissions_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_permissions',
            name='Given_By',
        ),
        migrations.RemoveField(
            model_name='page_permissions',
            name='user',
        ),
    ]
