# Generated by Django 3.2 on 2022-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0022_auto_20221104_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='custdt',
            name='Customer_Type',
            field=models.CharField(choices=[('Regular Customer', 'Regular Customer'), ('One Time Customer', 'One Time Customer')], max_length=50, null=True),
        ),
    ]
