# Generated by Django 3.2 on 2022-12-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0023_custdt_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_accounts',
            name='Account_No',
            field=models.CharField(help_text='Bank Account Number/UPI Phone Number', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bank_accounts',
            name='Account_Type',
            field=models.CharField(choices=[('Company Account', 'Company Account'), ('UPI Account', 'UPI Account')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bank_accounts',
            name='Bank_Name',
            field=models.CharField(help_text='Bank Name/UPI Holder Name', max_length=30, null=True),
        ),
    ]
