# Generated by Django 3.2 on 2022-12-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0025_bank_accounts_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_accounts',
            name='Account_Type',
            field=models.CharField(choices=[('Company', 'Company'), ('UPI', 'UPI'), ('CASH', 'CASH')], max_length=40, null=True),
        ),
    ]
