# Generated by Django 3.2.8 on 2022-09-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_salaries',
            name='Presents',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
