# Generated by Django 3.2.8 on 2022-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0003_monthly_salaries_presents'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_salaries',
            name='OT_Hours',
            field=models.FloatField(blank=True, help_text='over time hours if eligible', max_length=5, null=True),
        ),
    ]
