# Generated by Django 3.2.8 on 2022-07-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0003_monthly_salaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_salaries',
            name='OT_Amount',
            field=models.IntegerField(blank=True, help_text='over time amount if eligible', null=True),
        ),
    ]
