# Generated by Django 3.2.8 on 2022-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0004_monthly_salaries_ot_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_salaries',
            name='Presents',
        ),
        migrations.AddField(
            model_name='monthly_salaries',
            name='Actual_Net_Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthly_salaries',
            name='Expenses',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='monthly_salaries',
            name='Issued_Days',
            field=models.FloatField(blank=True, default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_salaries',
            name='Issued_Salary',
            field=models.IntegerField(blank=True, default=0, help_text='issued salary or net salary for this month', null=True),
        ),
        migrations.AlterField(
            model_name='monthly_salaries',
            name='LOP',
            field=models.FloatField(blank=True, default=0, help_text='loss of pay if eligible', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_salaries',
            name='OT_Amount',
            field=models.IntegerField(blank=True, default=0, help_text='over time amount if eligible', null=True),
        ),
        migrations.AlterField(
            model_name='monthly_salaries',
            name='OT_Hours',
            field=models.FloatField(blank=True, default=0, help_text='over time hours if eligible', max_length=5, null=True),
        ),
    ]
