# Generated by Django 3.2.8 on 2022-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0004_alter_monthly_salaries_ot_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_salaries',
            name='Pofessional_Tax',
        ),
        migrations.AddField(
            model_name='monthly_salaries',
            name='Professional_Tax',
            field=models.FloatField(blank=True, default=0, help_text='PT deductions if eligible, <15K 0, 15-20K 150, >15K 200 of gross', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_salaries',
            name='ESI_Employee',
            field=models.FloatField(blank=True, default=0, help_text='3.25% employer on gross', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_salaries',
            name='ESI_Employer',
            field=models.FloatField(blank=True, default=0, help_text='0.75% employee on gross', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_salaries',
            name='PF_Employee',
            field=models.FloatField(blank=True, default=0, help_text='PF employee share 12% of basic if eligible', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_salaries',
            name='PF_Employer',
            field=models.FloatField(blank=True, default=0, help_text='PF employer share 12% of basic if eligible', max_length=10, null=True),
        ),
    ]
