# Generated by Django 3.2.8 on 2022-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0005_auto_20220728_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Total_Amount',
            field=models.FloatField(blank=True, default=0, help_text='amount in rupees', max_length=10, null=True),
        ),
    ]
