# Generated by Django 3.2 on 2022-11-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0022_auto_20221104_1458'),
        ('Debits', '0005_auto_20221112_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debit_amounts',
            old_name='Related_Company',
            new_name='RC',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Related_Company',
            new_name='RC',
        ),
        migrations.AddField(
            model_name='attendance',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='declaredayas',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='month_sal_exp',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='monthatnd',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='monthly_salaries',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='working_days',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
    ]
