# Generated by Django 3.2.8 on 2022-07-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0006_alter_expenses_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Total_Amount',
            field=models.FloatField(blank=True, help_text='amount in rupees', max_length=10, null=True),
        ),
    ]
