# Generated by Django 3.2 on 2022-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0006_auto_20221119_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Is_Extra_Day',
            field=models.BooleanField(default=False, help_text='tru if holiday work as ot'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Is_No_Sunday',
            field=models.BooleanField(default=False, help_text='generated maunaully or automatically'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='OT',
            field=models.FloatField(blank=True, default=0, max_length=5, null=True),
        ),
    ]
