# Generated by Django 3.2.8 on 2022-08-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0007_alter_expenses_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Start_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
