# Generated by Django 3.2 on 2022-12-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0008_auto_20221214_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debit_amounts',
            name='Cheque_Details',
        ),
        migrations.AddField(
            model_name='debit_amounts',
            name='Reference_No',
            field=models.CharField(blank=True, help_text='cheque number/transaction number etc if available', max_length=60, null=True),
        ),
    ]
