# Generated by Django 3.2.8 on 2022-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0008_alter_attendance_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Is_Manual',
            field=models.BooleanField(default=True, help_text='generated maunaully or automatically'),
        ),
        migrations.AlterField(
            model_name='debit_amounts',
            name='Related_To',
            field=models.CharField(blank=True, choices=[('Services', 'Services'), ('Marketing', 'Marketing'), ('Office', 'Office'), ('Salary Advance', 'Salary Advance'), ('Dispatches', 'Dispatches'), ('Others', 'Others')], max_length=30, null=True),
        ),
    ]
