# Generated by Django 3.2.8 on 2022-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0011_auto_20220821_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_salaries',
            name='Status',
        ),
        migrations.AddField(
            model_name='expenses',
            name='Balance_Advance',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='monthly_salaries',
            name='Automatic',
            field=models.BooleanField(default=True),
        ),
    ]
