# Generated by Django 3.2.8 on 2022-08-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debits', '0012_auto_20220822_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Balance_Advance',
            field=models.FloatField(blank=True, default=0, help_text='if any advance at that time', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Balance_Amount',
            field=models.FloatField(blank=True, help_text='due amount', max_length=10, null=True),
        ),
    ]
