# Generated by Django 3.2.8 on 2022-05-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='Additional_Cost',
        ),
    ]
