# Generated by Django 3.2.8 on 2022-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='Cost_to_Client',
            field=models.FloatField(blank=True, help_text='Cost to Client', max_length=10, null=True),
        ),
    ]
