# Generated by Django 3.2.8 on 2022-04-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0002_quote_cost_to_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='Cost_to_Client',
            new_name='Cost_To_Client',
        ),
    ]
