# Generated by Django 3.2.8 on 2022-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0003_rename_cost_to_client_quote_cost_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='Power_Bill',
            field=models.CharField(blank=True, choices=[('Less than 1000', 'Less than 1000'), ('1000 to 3000', '1000 to 3000'), ('3000 to 6000', '3000 to 6000'), ('Above 6000', 'Above 6000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], help_text='Choose Wether it Resedential or Commercial', max_length=40, null=True),
        ),
    ]
