# Generated by Django 3.2.8 on 2022-04-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0004_auto_20220427_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='Capacity',
            field=models.ForeignKey(blank=True, help_text='Choose Your Required Capacity in KW', null=True, on_delete=django.db.models.deletion.CASCADE, to='Proposals.powercat'),
        ),
    ]
