# Generated by Django 3.2.8 on 2022-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0005_alter_proposal_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='Phone_Number',
            field=models.CharField(help_text='10 Digit Main Phone Number', max_length=10, null=True),
        ),
    ]
