# Generated by Django 3.2.8 on 2022-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0006_alter_proposal_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='Inverter_Capacity',
            field=models.IntegerField(blank=True, help_text='Capacity in KW such as 1, 2, 3, 5, 7 KW', null=True),
        ),
    ]
