# Generated by Django 3.2.8 on 2022-04-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Full Name', max_length=50, null=True, unique=True)),
                ('Short_Name', models.CharField(blank=True, help_text='Nick Name or Short Name', max_length=15, null=True, unique=True)),
                ('E_Id', models.CharField(blank=True, help_text='Employee ID', max_length=15, null=True, unique=True)),
                ('Designation', models.CharField(help_text='Employee Designation', max_length=100, null=True)),
                ('Department', models.CharField(blank=True, help_text='Department', max_length=100, null=True)),
                ('Phone_Number', models.CharField(help_text='10 Digit Main Phone Number', max_length=10, null=True)),
            ],
        ),
    ]
