# Generated by Django 3.2.8 on 2022-07-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empl_Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gross_Salary', models.IntegerField(help_text='gross salary or CTC', null=True)),
                ('Basic', models.IntegerField(help_text='basic salary as per govt norms', null=True)),
                ('HRA', models.FloatField(blank=True, help_text='house rent allowance, 40% of basic', max_length=10, null=True)),
                ('Other_Allowances', models.FloatField(blank=True, help_text='other allowances', max_length=10, null=True)),
                ('Net_Salary', models.IntegerField(help_text='by hand or net salary', null=True)),
                ('UAN_Number', models.CharField(blank=True, help_text='PF/UAN number if eligible', max_length=12, null=True)),
                ('ESI_Number', models.CharField(blank=True, help_text='ESI number if eligible', max_length=10, null=True)),
                ('PAN_Number', models.CharField(blank=True, help_text='PAN card number', max_length=10, null=True)),
                ('Aadhaar_Number', models.CharField(blank=True, help_text='PAN card number', max_length=12, null=True)),
                ('Status', models.BooleanField(default=True, help_text='active status')),
                ('Employ_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.account', unique=True)),
            ],
        ),
    ]
