# Generated by Django 3.2.8 on 2022-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0002_account_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='User_Name',
            field=models.CharField(help_text='Allocated User Name', max_length=30, null=True, unique=True),
        ),
    ]
