# Generated by Django 3.2.8 on 2022-07-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0002_empl_salaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empl_Salary_Revisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Revised_Date', models.DateField(help_text='salary revision date', null=True)),
                ('Revised_Gross', models.IntegerField(help_text='revised gross salary or CTC', null=True)),
                ('Revised_Basic', models.IntegerField(blank=True, help_text='revised basic salary if revised, otherwise it will take previous basic', null=True)),
                ('Next_Revision_Date', models.DateField(blank=True, help_text='salary next revision date, if leave it as blank, it will take a year after date', null=True)),
                ('Status', models.BooleanField(default=True, help_text='active status')),
                ('Employ_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.account')),
            ],
        ),
    ]
