# Generated by Django 3.2.8 on 2022-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0003_empl_salary_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='empl_salaries',
            name='ESI_Eligibility',
            field=models.BooleanField(default=True, help_text='mark if ESI eligible'),
        ),
        migrations.AddField(
            model_name='empl_salaries',
            name='OT_Eligibility',
            field=models.BooleanField(default=True, help_text='mark if ESI eligible'),
        ),
        migrations.AddField(
            model_name='empl_salaries',
            name='PF_Eligibility',
            field=models.BooleanField(default=True, help_text='mark if PF eligible'),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='Status',
            field=models.BooleanField(default=False, help_text='overtime eleigibility'),
        ),
    ]
