# Generated by Django 3.2.8 on 2022-07-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0004_auto_20220728_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empl_salaries',
            name='ESI_Eligibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='OT_Eligibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='PF_Eligibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
