# Generated by Django 3.2.8 on 2022-04-22 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAccounts', '0004_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='E_Id',
            new_name='Employee_Id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Short_Name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='User_Name',
        ),
        migrations.AddField(
            model_name='account',
            name='Nick_Name',
            field=models.CharField(blank=True, help_text='Nick Name or Short Name', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Upload_Photo',
            field=models.FileField(blank=True, help_text='Upload Your Photo', upload_to='employeephotos/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='Designation',
            field=models.CharField(blank=True, help_text='Employee Designation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Phone_Number',
            field=models.CharField(blank=True, help_text='10 Digit Phone Number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.BooleanField(default=False, help_text='Admin Permissions - All Access')),
                ('Main_Dashboard', models.BooleanField(default=False, help_text='Orders, Payments and Its Statestics View Permissions')),
                ('Proposals_Dashboard', models.BooleanField(default=False, help_text='Proposal Dashboard View Permissions')),
                ('Only_Expenses', models.BooleanField(default=False, help_text='Only Expenses (Rest All Dashboards Disabled) View Permissions')),
                ('Create', models.BooleanField(default=False, help_text='Create Permissions for Selected Dashboards')),
                ('Edit', models.BooleanField(default=False, help_text='Orders, Bills, Payments Edit Permissions')),
                ('Delete', models.BooleanField(default=False, help_text='Orders, Bills, Payments Edit Permissions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
