# Generated by Django 3.2.8 on 2022-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0005_auto_20220728_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='empl_salaries',
            name='ESI_Amount',
            field=models.FloatField(blank=True, default=0, help_text='ESI employee share if eligible', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empl_salaries',
            name='PF_Amount',
            field=models.FloatField(blank=True, default=0, help_text='PF employee share if eligible', max_length=10, null=True),
        ),
    ]
