# Generated by Django 3.2.8 on 2022-04-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0005_auto_20220422_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Department',
            field=models.CharField(blank=True, help_text='Leave as blank if not available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Designation',
            field=models.CharField(blank=True, help_text='Leave as blank if not available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Employee_Id',
            field=models.CharField(blank=True, help_text='Leave as blank if not available', max_length=15, null=True, unique=True),
        ),
    ]
