# Generated by Django 3.2.8 on 2022-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0006_auto_20220422_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Nick_Name',
            field=models.CharField(help_text='Nick Name or Short Name', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Phone_Number',
            field=models.CharField(help_text='10 Digit Phone Number', max_length=10, null=True),
        ),
    ]
