# Generated by Django 3.2.8 on 2022-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0006_auto_20220728_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empl_salaries',
            name='ESI_Amount',
            field=models.FloatField(blank=True, default=0, help_text='total 24% of basic, 12% employee, 12% employer', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='PF_Amount',
            field=models.FloatField(blank=True, default=0, help_text='total 4% of gross, 0.75% employee, 3.25% employer', max_length=10, null=True),
        ),
    ]
