# Generated by Django 3.2.8 on 2022-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0007_auto_20220728_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='empl_salaries',
            name='Professional_Tax',
            field=models.FloatField(blank=True, default=0, help_text='PT deductions if eligible', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='Net_Salary',
            field=models.IntegerField(blank=True, help_text='by hand or net salary', null=True),
        ),
    ]
