# Generated by Django 3.2.8 on 2022-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0007_auto_20220423_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='Only_Expenses',
            new_name='Expenses_Dashboard',
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Delete',
            field=models.BooleanField(default=False, help_text='Delete Permissions for Selected Dashboards'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Edit',
            field=models.BooleanField(default=False, help_text='Edit Permissions for Selected Dashboards'),
        ),
    ]
