# Generated by Django 3.2.8 on 2022-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0008_auto_20220425_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='Expenses_Dashboard',
            field=models.BooleanField(default=False, help_text='Expenses Dashboard View Permissions'),
        ),
    ]
