# Generated by Django 3.2.8 on 2022-07-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0009_auto_20220728_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='empl_salaries',
            name='Next_Revision_Date',
            field=models.DateField(blank=True, help_text='salary next revision date, if leave it as blank, it will take a year after date', null=True),
        ),
        migrations.AddField(
            model_name='empl_salaries',
            name='Revision_Status',
            field=models.BooleanField(default=False, help_text='mark if revised salary in his employement history'),
        ),
        migrations.AddField(
            model_name='empl_salary_revisions',
            name='Previous_Basic',
            field=models.IntegerField(blank=True, help_text='revised basic salary if revised, otherwise it will take previous basic', null=True),
        ),
        migrations.AddField(
            model_name='empl_salary_revisions',
            name='Previous_Date',
            field=models.DateField(blank=True, help_text='salary revision date', null=True),
        ),
        migrations.AddField(
            model_name='empl_salary_revisions',
            name='Previous_Gross',
            field=models.IntegerField(blank=True, help_text='revised gross salary or CTC', null=True),
        ),
    ]
