# Generated by Django 3.2.8 on 2022-07-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0010_auto_20220728_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empl_salary_revisions',
            old_name='Revised_Date',
            new_name='Revision_Date',
        ),
    ]
