# Generated by Django 3.2.8 on 2022-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0011_rename_firsr_name_account_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='account',
            name='Name',
            field=models.CharField(blank=True, help_text='Nick Name or Short Name', max_length=30, null=True),
        ),
    ]
