# Generated by Django 3.2.8 on 2022-08-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0011_rename_revised_date_empl_salary_revisions_revision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Sr_No',
            field=models.IntegerField(blank=True, help_text='employee id only serial number', null=True, unique=True),
        ),
    ]
