# Generated by Django 3.2.8 on 2022-08-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0012_account_sr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
