# Generated by Django 3.2.8 on 2022-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0012_auto_20220425_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ds',
            field=models.BooleanField(default=True),
        ),
    ]
