# Generated by Django 3.2.8 on 2022-04-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0013_account_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Name',
            field=models.CharField(help_text='Full Name', max_length=30, null=True),
        ),
    ]
