# Generated by Django 3.2.8 on 2022-08-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0013_account_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['Sr_No']},
        ),
        migrations.RemoveField(
            model_name='empl_salary_revisions',
            name='Revision_Date',
        ),
        migrations.AddField(
            model_name='empl_salary_revisions',
            name='Effective_From',
            field=models.DateField(help_text='salary revision effective from', null=True),
        ),
    ]
