# Generated by Django 3.2.8 on 2022-07-07 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAccounts', '0014_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Joining_Date',
            field=models.DateField(blank=True, help_text='date of joining', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Relationship',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Status',
            field=models.BooleanField(default=True, help_text='unmark if he is not active/leave organisation'),
        ),
        migrations.AddField(
            model_name='account',
            name='Support',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Field', 'Field'), ('Offline', 'Offline')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Department',
            field=models.CharField(blank=True, help_text='leave as blank if not available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Designation',
            field=models.CharField(blank=True, help_text='leave as blank if not available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Employee_Id',
            field=models.CharField(blank=True, help_text='employee id or serial number', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Name',
            field=models.CharField(help_text='full name of the employee including sir name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Nick_Name',
            field=models.CharField(help_text='short calling name or nick name', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Phone_Number',
            field=models.CharField(help_text='contact number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Upload_Photo',
            field=models.FileField(blank=True, help_text='upload employee photo', upload_to='employes/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EMP_More_Dtls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Father_Name', models.CharField(blank=True, help_text='employee father name', max_length=50, null=True)),
                ('Phone_Personal', models.CharField(blank=True, help_text='personal contact number', max_length=10, null=True)),
                ('Phone_Relative', models.CharField(blank=True, help_text='father/relative reference number', max_length=10, null=True)),
                ('Aadhaar_No', models.CharField(blank=True, help_text='aadhaar no', max_length=12, null=True, unique=True)),
                ('PAN_No', models.CharField(blank=True, help_text='pan card no', max_length=10, null=True, unique=True)),
                ('DOB', models.DateField(blank=True, help_text='date of birth', null=True)),
                ('Upload_Resume', models.FileField(blank=True, help_text='upload pan copy', upload_to='employes/resumes/')),
                ('Upload_Aadhaar', models.FileField(blank=True, help_text='upload adhaar copy', upload_to='employes/aadhaar/')),
                ('Upload_PAN', models.FileField(blank=True, help_text='upload pan copy', upload_to='employes/pan/')),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='EMP_End_Dtls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Releaving_Date', models.DateField(blank=True, help_text='date of releaving', null=True)),
                ('Remarks', models.TextField(blank=True, help_text='remarks or conclusion about employee', max_length=500, null=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='EMP_Bank_Dtls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_No', models.CharField(help_text='bank account number', max_length=40, null=True)),
                ('Bank_Name', models.CharField(help_text='bank Name', max_length=30, null=True)),
                ('Branch', models.CharField(blank=True, help_text='bank branch details', max_length=40, null=True)),
                ('IFSC_Code', models.CharField(blank=True, help_text='bank IFSC code', max_length=11, null=True)),
                ('Account_Type', models.CharField(choices=[('Company', 'Company'), ('Personal', 'Personal')], max_length=20, null=True)),
                ('Status', models.BooleanField(default=True, help_text='active status')),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccounts.account')),
            ],
        ),
    ]
