# Generated by Django 3.2.8 on 2022-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0014_auto_20220803_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='empl_salaries',
            name='Effective_From',
            field=models.DateField(blank=True, help_text='salary effective from', null=True),
        ),
    ]
