# Generated by Django 3.2.8 on 2022-07-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0015_auto_20220707_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_more_dtls',
            name='Father_Name',
        ),
        migrations.RemoveField(
            model_name='emp_more_dtls',
            name='Phone_Personal',
        ),
        migrations.RemoveField(
            model_name='emp_more_dtls',
            name='Phone_Relative',
        ),
        migrations.AddField(
            model_name='account',
            name='Email',
            field=models.CharField(blank=True, help_text='official email or personal email', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emp_more_dtls',
            name='Alternative_Phone',
            field=models.CharField(blank=True, help_text='alternative phone number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emp_bank_dtls',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccounts.account'),
        ),
        migrations.AlterField(
            model_name='emp_more_dtls',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccounts.account'),
        ),
    ]
