# Generated by Django 3.2.8 on 2022-11-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0021_auto_20221104_1449'),
        ('UserAccounts', '0015_empl_salaries_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
    ]
