# Generated by Django 3.2.8 on 2022-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0016_auto_20220708_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Email',
            field=models.EmailField(blank=True, help_text='official email or personal email', max_length=50, null=True),
        ),
    ]
