# Generated by Django 3.2.8 on 2022-11-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0022_auto_20221104_1458'),
        ('UserAccounts', '0018_auto_20221104_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_pages',
            name='RC',
        ),
        migrations.AddField(
            model_name='edit_pages',
            name='RC',
            field=models.ManyToManyField(blank=True, null=True, to='Projects.CompanyDetails'),
        ),
        migrations.RemoveField(
            model_name='edit_pages',
            name='Related_Project',
        ),
        migrations.AddField(
            model_name='edit_pages',
            name='Related_Project',
            field=models.ManyToManyField(blank=True, help_text='leave empty if product meant for many projects', null=True, to='Projects.Projects'),
        ),
        migrations.RemoveField(
            model_name='view_pages',
            name='RC',
        ),
        migrations.AddField(
            model_name='view_pages',
            name='RC',
            field=models.ManyToManyField(blank=True, null=True, to='Projects.CompanyDetails'),
        ),
        migrations.RemoveField(
            model_name='view_pages',
            name='Related_Project',
        ),
        migrations.AddField(
            model_name='view_pages',
            name='Related_Project',
            field=models.ManyToManyField(blank=True, help_text='leave empty if product meant for many projects', null=True, to='Projects.Projects'),
        ),
    ]
