# Generated by Django 3.2.8 on 2022-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0022_auto_20221104_1458'),
        ('UserAccounts', '0019_auto_20221109_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Modes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page', models.CharField(blank=True, max_length=100, null=True)),
                ('Mode', models.ManyToManyField(blank=True, null=True, to='UserAccounts.Page_Modes')),
                ('RC', models.ManyToManyField(blank=True, null=True, to='Projects.CompanyDetails')),
                ('Related_Project', models.ManyToManyField(blank=True, help_text='leave empty if product meant for many projects', null=True, to='Projects.Projects')),
            ],
        ),
        migrations.RemoveField(
            model_name='page_permissions',
            name='Edit_Permissions',
        ),
        migrations.RemoveField(
            model_name='page_permissions',
            name='View_Permissions',
        ),
        migrations.DeleteModel(
            name='View_Pages',
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='Permissions',
            field=models.ManyToManyField(blank=True, null=True, to='UserAccounts.Pages'),
        ),
    ]
