# Generated by Django 3.2.8 on 2022-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0020_auto_20221109_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empl_salaries',
            name='Basic',
            field=models.IntegerField(default=0, help_text='basic salary as per govt norms', null=True),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='Gross_Salary',
            field=models.IntegerField(default=0, help_text='gross salary or CTC', null=True),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='HRA',
            field=models.FloatField(blank=True, default=0, help_text='house rent allowance, 40% of basic', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='Net_Salary',
            field=models.IntegerField(blank=True, default=0, help_text='you can give it or we will calculate', null=True),
        ),
        migrations.AlterField(
            model_name='empl_salaries',
            name='Other_Allowances',
            field=models.FloatField(blank=True, default=0, help_text='other allowances', max_length=10, null=True),
        ),
    ]
