# Generated by Django 3.2.8 on 2022-11-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0021_auto_20221112_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_permissions',
            name='Permissions',
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='View_Permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('Mode__Mode__in', ['Edit'])), null=True, related_name='edit', to='UserAccounts.Pages'),
        ),
    ]
