# Generated by Django 3.2 on 2022-11-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0023_auto_20221114_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_Pages',
        ),
    ]
