# Generated by Django 3.2 on 2022-11-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0022_auto_20221104_1458'),
        ('UserAccounts', '0024_delete_edit_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='Related_Project',
        ),
        migrations.AddField(
            model_name='pages',
            name='Related_Project',
            field=models.ForeignKey(blank=True, help_text='leave empty if product meant for many projects', null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.projects'),
        ),
    ]
