# Generated by Django 3.2 on 2022-11-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0025_auto_20221117_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='RC',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='Related_Project',
        ),
        migrations.AddField(
            model_name='pages',
            name='Category',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Contact Management', 'Contact Management'), ('Expenses', 'Expenses'), ('Purchases', 'Purchases'), ('Sales', 'Sales'), ('GST', 'GST')], max_length=30, null=True),
        ),
    ]
