# Generated by Django 3.2 on 2022-11-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0022_auto_20221104_1458'),
        ('UserAccounts', '0026_auto_20221119_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_permissions',
            name='RC',
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.RemoveField(
            model_name='page_permissions',
            name='Related_Project',
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='Related_Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='Category',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Contact Management', 'Contact Management'), ('Expenses', 'Expenses'), ('Products', 'Products'), ('Purchases', 'Purchases'), ('Sales', 'Sales'), ('GST', 'GST')], max_length=30, null=True),
        ),
    ]
