# Generated by Django 3.2 on 2022-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0028_upi_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Is_Super_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
