# Generated by Django 3.2 on 2022-12-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0026_alter_bank_accounts_account_type'),
        ('UserAccounts', '0029_account_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Related_Project',
            field=models.ManyToManyField(blank=True, null=True, to='Projects.Projects'),
        ),
    ]
