# Generated by Django 3.2.8 on 2022-05-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0011_alter_vendcontdt_supplier_name'),
        ('UserAccounts', '0014_alter_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Details', models.TextField(blank=True, help_text='overall order short description', max_length=1000, null=True)),
                ('Order_Value', models.FloatField(blank=True, help_text='order value or estimated value excluding taxes', max_length=20, null=True)),
                ('Order_Type', models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Pipeline', 'Pipeline')], max_length=20, null=True)),
                ('Order_Received_Date', models.DateTimeField(blank=True, help_text='Received Order Date', null=True)),
                ('Order_Through', models.CharField(blank=True, choices=[('By PO', 'By PO'), ('By Mail', 'By Mail'), ('By Phone', 'By Phone')], max_length=20, null=True)),
                ('Status', models.BooleanField(default=False, help_text='tick if completed')),
                ('Attach', models.FileField(blank=True, help_text='attach order copies if available', null=True, upload_to='orders/')),
                ('ds', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Description', models.TextField(help_text='product details', max_length=1000, null=True, unique=True)),
                ('Quantity', models.IntegerField(blank=True, help_text='Quantity', null=True)),
                ('UOM', models.CharField(blank=True, help_text='units such as Nos, sets etc...', max_length=20, null=True, unique=True)),
                ('Unit_Price', models.FloatField(blank=True, help_text='each UOM/unit price excluding GST/Tax', max_length=15, null=True)),
                ('GST', models.FloatField(blank=True, help_text='GST in % such as 12, 18 etc', max_length=10, null=True)),
                ('TDS', models.FloatField(blank=True, help_text='If any Service Tax/TDS applicable', max_length=10, null=True)),
                ('Order_No', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='Add_Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.sales_product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Customer_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.custdt'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Order_Reference_Person',
            field=models.ForeignKey(help_text='order reference person name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.custcontdt'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Related_Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.account'),
        ),
    ]
