# Generated by Django 3.2.8 on 2022-07-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        ('Products', '0001_initial'),
        ('Projects', '0001_initial'),
        ('UserAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='Add_Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.products'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='Order_No',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Bank_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.bank_accounts'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Billing_From',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing', to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Billing_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='Projects.custdt'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Delivery_Note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.delivery_note'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Invoice_No_Format',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('No_Format_Related_To__in', ['Invoice', 'Proforma Invoice'])), null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.no_formats'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.orders'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Payment_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.payment_status'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Shipping_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.custdt'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='Terms_and_Conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.terms_conditions'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.account'),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='Invoice_No',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.invoices'),
        ),
        migrations.AddField(
            model_name='copy_billed_items',
            name='Invoice_No',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.invoices'),
        ),
        migrations.AddField(
            model_name='copy_billed_items',
            name='Item_From_Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.billed_items'),
        ),
        migrations.AddField(
            model_name='billed_items',
            name='Add_Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product_price'),
        ),
        migrations.AddField(
            model_name='billed_items',
            name='Invoice_No',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.invoices'),
        ),
        migrations.AddField(
            model_name='billed_items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.account'),
        ),
    ]
