# Generated by Django 3.2.8 on 2022-07-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='Payment_Terms',
            field=models.CharField(blank=True, help_text='payment terms', max_length=100, null=True),
        ),
    ]
