# Generated by Django 3.2.8 on 2022-10-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0015_auto_20221021_1806'),
        ('Orders', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillRefNo',
        ),
        migrations.DeleteModel(
            name='OrderRefNo',
        ),
        migrations.AddField(
            model_name='orders',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AlterField(
            model_name='billed_items',
            name='Quantity',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='copy_billed_items',
            name='CESS',
            field=models.FloatField(blank=True, default=0, help_text='CESS in % if applicable', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='copy_billed_items',
            name='GST',
            field=models.FloatField(blank=True, default=0, help_text='GST in % such as 12, 18 etc', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='copy_billed_items',
            name='Other_Taxes',
            field=models.FloatField(blank=True, default=0, help_text='specify if any other taxes in % only', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='copy_billed_items',
            name='Quantity',
            field=models.FloatField(default=0, help_text='quantity', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='copy_billed_items',
            name='Unit_Price',
            field=models.FloatField(blank=True, default=0, help_text='each unit price excluding all taxes', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='CESS_Amount',
            field=models.FloatField(blank=True, default=0, help_text='CESS Amount', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='GST_Amount',
            field=models.FloatField(blank=True, default=0, help_text='only GST Amount', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='Quantity',
            field=models.FloatField(default=0, help_text='no of items', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_Value',
            field=models.FloatField(blank=True, default=0, help_text='order value or estimated value', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment_status',
            name='As_Advance_Amount',
            field=models.FloatField(blank=True, default=0, help_text='If any as advance after clear all bills', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment_status',
            name='Received_Amount',
            field=models.FloatField(blank=True, default=0, help_text='received payment against this order', max_length=20, null=True),
        ),
    ]
