# Generated by Django 3.2.16 on 2023-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Attach_Excels',
            field=models.FileField(blank=True, help_text='attach excel copy if available', null=True, upload_to='orders/'),
        ),
    ]
