# Generated by Django 3.2.8 on 2022-10-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0018_auto_20221025_1220'),
        ('Orders', '0003_auto_20221021_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_tc',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
    ]
