# Generated by Django 3.2.8 on 2022-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_invoices_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='Invoice_No',
            field=models.CharField(blank=True, help_text='invoice/bill no', max_length=30, null=True),
        ),
    ]
