# Generated by Django 3.2.8 on 2022-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_invoices_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='Invoice_Amount',
            field=models.FloatField(blank=True, default=0, help_text='including all taxes', max_length=20, null=True),
        ),
    ]
