# Generated by Django 3.2.8 on 2022-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_sales_tc_rc'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='Roundoff',
            field=models.FloatField(blank=True, default=0, max_length=5, null=True),
        ),
    ]
