# Generated by Django 3.2.8 on 2022-08-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_invoices_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='Last_Update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
