# Generated by Django 3.2.8 on 2022-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_invoices_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='GST_Returns_Date',
            field=models.DateField(blank=True, help_text='returns month/date, by default its invoice date', null=True),
        ),
    ]
