# Generated by Django 3.2.8 on 2022-07-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_invoices_invoice_no_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='PO_Status',
            field=models.BooleanField(default=False, help_text='PO work completion status, mark if PO work completed'),
        ),
    ]
