# Generated by Django 3.2 on 2022-12-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0028_upi_accounts'),
        ('Orders', '0007_auto_20221203_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_status',
            name='Reference_No',
            field=models.CharField(blank=True, help_text='transaction no/cheque no', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment_status',
            name='UPI_Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.upi_accounts'),
        ),
        migrations.DeleteModel(
            name='UPI_Accounts',
        ),
    ]
