# Generated by Django 3.2.8 on 2022-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_invoices_gst_returns_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='GST_Returns_Date',
        ),
        migrations.AddField(
            model_name='invoices',
            name='Amended_GST_Returns_Date',
            field=models.DateField(blank=True, help_text='any date in a month which you want make returns', null=True),
        ),
    ]
