# Generated by Django 3.2 on 2022-12-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0028_upi_accounts'),
        ('Orders', '0008_auto_20221205_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_status',
            name='Payment_Account',
            field=models.CharField(choices=[('HDFC', 'HDFC'), ('IDBI', 'IDBI'), ('UPI', 'UPI'), ('CASH', 'CASH')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment_status',
            name='UPI_Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.upi_accounts'),
        ),
    ]
