# Generated by Django 3.2 on 2022-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_auto_20221205_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='PO_No',
            field=models.CharField(help_text='Purchase Order Number if available', max_length=30, null=True),
        ),
    ]
