# Generated by Django 3.2 on 2022-12-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_alter_orders_po_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_Details',
            field=models.CharField(blank=True, help_text='overall order short description', max_length=500, null=True),
        ),
    ]
