# Generated by Django 3.2 on 2022-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_alter_orders_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='PO_No',
            field=models.CharField(help_text='internal received order number', max_length=30, null=True),
        ),
    ]
