# Generated by Django 3.2 on 2022-12-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0025_bank_accounts_balance'),
        ('Orders', '0013_auto_20221213_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_status',
            name='Account_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.bank_accounts'),
        ),
    ]
