# Generated by Django 3.2 on 2022-12-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0029_account_is_super_admin'),
        ('Projects', '0026_alter_bank_accounts_account_type'),
        ('Orders', '0014_alter_payment_status_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(help_text='customer/company name', max_length=50, null=True)),
                ('Phone_Number', models.CharField(help_text='Phone Number', max_length=20, null=True)),
                ('Quote_Short_Description', models.CharField(blank=True, help_text='overall order short description', max_length=500, null=True)),
                ('Quote_No', models.CharField(blank=True, help_text='internal purpose - quote reference number', max_length=30, null=True)),
                ('Quote_Value', models.FloatField(blank=True, default=0, help_text='order value or estimated value', max_length=20, null=True)),
                ('Date', models.DateTimeField(blank=True, help_text='received order date', null=True)),
                ('Attach', models.FileField(blank=True, help_text='attach quote copy if available', null=True, upload_to='manualquotes/')),
                ('ds', models.BooleanField(default=True)),
                ('RC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails')),
                ('Related_Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.account')),
            ],
        ),
    ]
