# Generated by Django 3.2 on 2022-12-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0026_alter_bank_accounts_account_type'),
        ('UserAccounts', '0029_account_is_super_admin'),
        ('Orders', '0015_manual_quote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manual_Quote',
            new_name='Manual_Quotes',
        ),
    ]
