# Generated by Django 3.2 on 2022-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_rename_manual_quote_manual_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual_quotes',
            name='Email',
            field=models.EmailField(blank=True, help_text='Email', max_length=50, null=True),
        ),
    ]
