# Generated by Django 3.2.8 on 2022-06-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='Warranty_In',
            field=models.CharField(blank=True, choices=[('Month', 'Months'), ('Year', 'Years'), ('Day', 'Days')], max_length=20, null=True),
        ),
    ]
