# Generated by Django 3.2.8 on 2022-07-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_purchases_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_terms_conditions',
            name='Terms_and_Condition1',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po_terms_conditions',
            name='Terms_and_Condition2',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po_terms_conditions',
            name='Terms_and_Condition3',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po_terms_conditions',
            name='Terms_and_Condition4',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po_terms_conditions',
            name='Terms_and_Condition5',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po_terms_conditions',
            name='Terms_and_Condition6',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po_terms_conditions',
            name='Terms_and_Condition7',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po_terms_conditions',
            name='Terms_and_Condition8',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_tc',
            name='Terms_and_Condition1',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_tc',
            name='Terms_and_Condition2',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_tc',
            name='Terms_and_Condition3',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_tc',
            name='Terms_and_Condition4',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_tc',
            name='Terms_and_Condition5',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_tc',
            name='Terms_and_Condition6',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_tc',
            name='Terms_and_Condition7',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_tc',
            name='Terms_and_Condition8',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True),
        ),
    ]
