# Generated by Django 3.2.8 on 2022-07-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20220729_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='PO_No',
            field=models.CharField(blank=True, help_text='PO No', max_length=30, null=True),
        ),
    ]
