# Generated by Django 3.2.8 on 2022-10-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_vendor_invoices_adjusted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_invoices',
            name='Adjusted_Amount',
            field=models.FloatField(blank=True, default=0, help_text='payment against another invoice if exceed, excess amount adjusted to this', max_length=10, null=True),
        ),
    ]
