# Generated by Django 3.2.8 on 2022-06-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20220629_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='PO_Status',
        ),
        migrations.AddField(
            model_name='purchases',
            name='Delivery_Status',
            field=models.BooleanField(default=False, help_text='PO delivery status, mark if material delivered'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='Payment_Final_Status',
            field=models.BooleanField(default=False),
        ),
    ]
