# Generated by Django 3.2.8 on 2022-06-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20220629_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='Attach',
        ),
        migrations.AlterField(
            model_name='vendor_invoices',
            name='Attach',
            field=models.FileField(blank=True, help_text='attach order copy if available', null=True, upload_to='vendorinvoices/'),
        ),
        migrations.AlterField(
            model_name='vendor_invoices',
            name='GST_Amount',
            field=models.FloatField(blank=True, help_text='only GST Amount, if no GST enter 0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_invoices',
            name='Invoice_Amount',
            field=models.FloatField(help_text='including all taxes', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_invoices',
            name='Invoice_Date',
            field=models.DateTimeField(help_text='billed date', null=True),
        ),
        migrations.AlterField(
            model_name='vendor_invoices',
            name='Invoice_No',
            field=models.CharField(help_text='vendor issued invoice no against po', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor_invoices',
            name='PO_No',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.purchases'),
        ),
    ]
