# Generated by Django 3.2.8 on 2022-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_copy_quote_items_quote_items_quote_tc_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_TC_Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taxes', models.CharField(blank=True, help_text='Ex: GST @ 18% (As Applicable)', max_length=50, null=True)),
                ('Payment_Terms', models.CharField(blank=True, help_text='Payment terms and conditions', max_length=150, null=True)),
                ('Delivery_Terms', models.CharField(blank=True, help_text='delivery details and terms', max_length=150, null=True)),
                ('Transport_Terms', models.CharField(blank=True, help_text='included/excluded or any other', max_length=100, null=True)),
                ('Validation_Terms', models.CharField(blank=True, help_text='prices/quote validation terms', max_length=100, null=True)),
                ('FOR', models.CharField(blank=True, help_text='Ex; FOR Hyderabad', max_length=100, null=True)),
                ('Other_Terms', models.CharField(blank=True, help_text='other terms if need to specify', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quotes',
            name='Quote_No',
            field=models.CharField(blank=True, help_text='Quote No', max_length=30, null=True, unique=True),
        ),
    ]
