# Generated by Django 3.2.8 on 2022-10-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0018_auto_20221025_1220'),
        ('Products', '0005_alter_vendor_invoices_adjusted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='purchase_tc',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
        migrations.AddField(
            model_name='quote_tc_default',
            name='RC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.companydetails'),
        ),
    ]
