# Generated by Django 3.2.8 on 2022-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20221025_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_invoices',
            name='Roundoff',
            field=models.FloatField(blank=True, default=0, max_length=5, null=True),
        ),
    ]
