# Generated by Django 3.2.8 on 2022-06-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0014_alter_account_name'),
        ('Products', '0006_auto_20220630_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO_Delivery_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_Date', models.DateTimeField(help_text='delivery date', null=True)),
                ('Is_Delivered_Fully', models.BooleanField(default=False, help_text='mark it if all material as per PO delevered')),
                ('Want_To_Close_PO', models.BooleanField(default=False, help_text=' mark it if not want futher delivery with this PO')),
                ('Next_Commitment_Date', models.DateField(blank=True, help_text='specify if any pending material and committed to deliver on coming date', null=True)),
                ('Remarks', models.TextField(blank=True, help_text='specify if any comments or remarks on delivery', max_length=500, null=True)),
                ('Attach', models.FileField(blank=True, help_text='attach if any delivery challan against PO delivery from vendor', null=True, upload_to='vendorinvoices/')),
                ('PO_No', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.purchases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAccounts.account')),
            ],
        ),
    ]
