# Generated by Django 3.2.8 on 2022-08-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20220809_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_tc',
            name='Quote_No',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.quotes'),
        ),
    ]
