# Generated by Django 3.2 on 2022-12-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_vendor_invoices_roundoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment_status',
            name='Payment_Account',
            field=models.CharField(blank=True, choices=[('HDFC', 'HDFC'), ('IDBI', 'IDBI'), ('UPI', 'UPI'), ('CASH', 'CASH')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor_payment_status',
            name='Reference_No',
            field=models.CharField(blank=True, help_text='transaction no/UPI mobile number/cheque no', max_length=30, null=True),
        ),
    ]
