# Generated by Django 3.2.8 on 2022-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_quote_tc_quote_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='Lock_Status',
            field=models.BooleanField(default=False, help_text='mark if wnat to lock quote to avoid editing'),
        ),
    ]
