# Generated by Django 3.2.8 on 2022-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20220630_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='Delivery_Status',
        ),
        migrations.AlterField(
            model_name='purchases',
            name='Delivery_Date',
            field=models.DateField(blank=True, help_text='required deliver date', null=True),
        ),
    ]
