# Generated by Django 3.2.8 on 2022-08-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_quotes_lock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_invoices',
            name='Last_Update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
