# Generated by Django 3.2.8 on 2022-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_vendor_invoices_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='Date',
            field=models.DateField(blank=True, help_text='quote date', null=True),
        ),
    ]
