# Generated by Django 3.2 on 2022-12-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20221214_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_payment_status',
            name='Paid_Amount',
            field=models.FloatField(blank=True, default=0, help_text='received payment against this order', max_length=20, null=True),
        ),
    ]
