# Generated by Django 3.2.8 on 2022-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_purchases_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='Delivery_Date',
            field=models.DateField(blank=True, help_text='payment due date', null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='Delivery_Status',
            field=models.BooleanField(default=False, help_text='PO delivery status, mark if material delivered'),
        ),
    ]
