# Generated by Django 3.2.8 on 2022-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_quotes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='Subject',
            field=models.TextField(blank=True, help_text='quote subject if necessary', max_length=500, null=True),
        ),
    ]
