# Generated by Django 3.2.8 on 2022-06-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_rename_delivery_status_purchases_delivery_status1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='Delivery_Status1',
            new_name='Delivery_Status',
        ),
    ]
