# Generated by Django 3.2.8 on 2022-08-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_quotes_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='Thanks_Note',
            field=models.TextField(blank=True, help_text='thanks giving text', max_length=500, null=True),
        ),
    ]
