# Generated by Django 3.2.8 on 2022-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_alter_quotes_thanks_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_invoices',
            name='GST_Returns_Date',
            field=models.DateField(blank=True, help_text='returns month/date, by default its invoice date', null=True),
        ),
        migrations.AddField(
            model_name='vendor_invoices',
            name='Set_For_Returns',
            field=models.BooleanField(default=True),
        ),
    ]
