# Generated by Django 3.2.8 on 2022-07-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20220703_1941'),
        ('Orders', '0007_alter_orders_po_status'),
        ('Products', '0015_auto_20220702_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_movement',
            old_name='Inward_Ref_PO',
            new_name='Related_PO',
        ),
        migrations.RemoveField(
            model_name='product_movement',
            name='Movement',
        ),
        migrations.RemoveField(
            model_name='product_movement',
            name='Related_Order',
        ),
        migrations.RemoveField(
            model_name='product_movement',
            name='Related_Project',
        ),
        migrations.RemoveField(
            model_name='products',
            name='BOM_No',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Serial_No',
        ),
        migrations.AddField(
            model_name='product_movement',
            name='Movement_Type',
            field=models.CharField(choices=[('Added', 'Added'), ('Substracted', 'Substracted')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product_movement',
            name='Related_Bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.invoices'),
        ),
        migrations.AddField(
            model_name='products',
            name='Active_From',
            field=models.DateField(blank=True, help_text='product active since', null=True),
        ),
        migrations.AlterField(
            model_name='copy_po_items',
            name='UOM',
            field=models.CharField(choices=[('No', 'Nos'), ('Set', 'Sets'), ('Kg', 'Kgs'), ('Mtr', 'Mtrs'), ('Ltr', 'Ltrs'), ('Bag', 'Bags')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product_movement',
            name='Date',
            field=models.DateField(blank=True, help_text='product added/updated date', null=True),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='HSN_Code',
            field=models.IntegerField(blank=True, help_text='HSN/SAC Code for this product', null=True),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='Unit_Price',
            field=models.FloatField(help_text='each unit price excluding all taxes', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Name',
            field=models.TextField(help_text='product name and its description', max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Related_Project',
            field=models.ForeignKey(blank=True, help_text='leave empty if product meant for many workareas/divisions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projects'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Status',
            field=models.BooleanField(default=True, help_text='present product active status'),
        ),
        migrations.AlterField(
            model_name='products',
            name='UOM',
            field=models.CharField(choices=[('No', 'Nos'), ('Set', 'Sets'), ('Kg', 'Kgs'), ('Mtr', 'Mtrs'), ('Ltr', 'Ltrs'), ('Bag', 'Bags')], max_length=15, null=True),
        ),
    ]
