# Generated by Django 3.2.8 on 2022-09-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_auto_20220903_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_invoices',
            old_name='GST_Returns_Date',
            new_name='Amended_GST_Returns_Date',
        ),
    ]
