# Generated by Django 3.2.8 on 2022-07-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_auto_20220703_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Model_No',
        ),
        migrations.AlterField(
            model_name='products',
            name='Make',
            field=models.CharField(blank=True, help_text='product make - optional', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='UOM',
            field=models.CharField(blank=True, choices=[('No', 'Nos'), ('Set', 'Sets'), ('Kg', 'Kgs'), ('Mtr', 'Mtrs'), ('Ltr', 'Ltrs'), ('Bag', 'Bags')], max_length=15, null=True),
        ),
    ]
