# Generated by Django 3.2.8 on 2022-07-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_auto_20220704_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='Attach',
            field=models.FileField(blank=True, help_text='attach po copies if available', null=True, upload_to='manualpos/'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='GST_Amount',
            field=models.FloatField(blank=True, help_text='only GST Amount, if no GST enter 0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='Is_Manual',
            field=models.BooleanField(default=False, help_text='wether it is manual entry or online generation'),
        ),
    ]
